### ISSUE TITLE
其他GPU架构的推理

### ISSUE THREAD

**Issue by NoobPythoner** [Lizonghang/TPI-LLM#3]
如题，边缘设备也可以带一些低端显卡（矿卡），像现在手机都有各种型号GPU，大概率边缘设备部署不会直接跑在CPU上的

**Comment by Lizonghang** [comment]
TPI-LLM使用PyTotch作为计算引擎，理论上，PyTorch支持的基于共享内存的集显都可以使用，比如Mac Metal Graphics，只要让PyTorch在MPS上运行且你拥有多台支持MPS的笔记本。
